INSERT INTO public.fighters ("fighter", "rosterId", "displayName")
  VALUES
    ('banjo', 80, 'Banjo & Kazooie'),
    ('bayonetta', 69, 'Bayonetta'),
    ('bowser', 16, 'Bowser'),
    ('bowserJr', 63, 'Bowser Jr'),
    ('byleth', 82, 'Byleth'),
    ('captainFalcon', 12, 'Captain Falcon'),
    ('chrom', 29, 'Chrom'),
    ('cloud', 67, 'Cloud'),
    ('corrin', 68, 'Corrin'),
    ('daisy', 15, 'Daisy'),
    ('darkPit', 33, 'Dark Pit'),
    ('darkSamus', 5, 'Dark Samus'),
    ('diddy', 39, 'Diddy Kong'),
    ('donkey', 2, 'Donkey Kong'),
    ('drMario', 20, 'Dr. Mario'),
    ('duckHunt', 64, 'Duck Hunt'),
    ('falco', 22, 'Falco'),
    ('fox', 8, 'fox'),
    ('ganon', 26, 'Ganondorf'),
    ('greninja', 55, 'Greninja'),
    ('hero', 79, 'Hero'),
    ('inkling', 70, 'Inkling'),
    ('joker', 78, 'Joker');
