INSERT INTO public.fighters ("fighter", "rosterId", "displayName")
  VALUES
    ('banjo', 80, 'Banjo & Kazooie'),
    ('bayonetta', 69, 'Bayonetta'),
    ('bowser', 16, 'Bowser'),
    ('bowserJr', 63, 'Bowser Jr'),
    ('byleth', 82, 'Byleth'),
    ('captainFalcon', 12, 'Captain Falcon'),
    ('chrom', 29, 'Chrom'),
    ('cloud', 67, 'Cloud'),
    ('corrin', 68, 'Corrin'),
    ('daisy', 15, 'Daisy'),
    ('darkPit', 33, 'Dark Pit'),
    ('darkSamus', 5, 'Dark Samus'),
    ('diddy', 41, 'Diddy Kong'),
    ('donkey', 2, 'Donkey Kong'),
    ('drMario', 20, 'Dr. Mario'),
    ('duckHunt', 64, 'Duck Hunt'),
    ('falco', 22, 'Falco'),
    ('fox', 8, 'fox'),
    ('ganon', 26, 'Ganondorf'),
    ('greninja', 55, 'Greninja'),
    ('hero', 79, 'Hero'),
    ('iceClimbers', 17, 'Ice Climbers'),
    ('ike', 37, 'Ike'),
    ('incineroar', 76, 'Incineroar'),
    ('inkling', 70, 'Inkling'),
    ('isabelle', 75, 'Isabelle'),
    ('jigglypuff', 13, 'Jigglypuff'),
    ('joker', 78, 'Joker'),
    ('kazuya', 88, 'Kazuya'),
    ('ken', 66, 'Ken'),
    ('kingDedede', 44, 'King Dedede'),
    ('kingKrool', 74, 'King K. Rool'),
    ('kirby', 7, 'Kirby'),
    ('link', 3, 'Link'),
    ('littleMac', 54, 'Little Mac'),
    ('lucario', 46, 'Lucario'),
    ('lucas', 42, 'Lucas'),
    ('lucina', 24, 'Lucina'),
    ('luigi', 10, 'Luigi'),
    ('mario', 1, 'Mario'),
    ('marth', 23, 'Marth'),
    ('megaMan', 51, 'Mega Man'),
    ('metaKnight', 31, 'Meta Knight'),
    ('mewtwo', 27, 'Mewtwo'),
    ('miiBrawler', 56, 'Mii Brawler'),
    ('miiGunner', 57, 'Mii Gunner'),
    ('miiSwordfighter', 58, 'Mii Swordfighter'),
    ('minmin', 83, 'Min Min'),
    ('mrGameAndWatch', 30, 'Mr. Game & Watch'),
    ('mythra', 87, 'Mythra'),
    ('ness', 11, 'Ness'),
    ('olimar', 45, 'Olimar'),
    ('pacMan', 60, 'Pac Man'),
    ('palutena', 59, 'Palutena'),
    ('peach', 14, 'Peach'),
    ('pichu', 21, 'Pichu'),
    ('pikachu', 9, 'Pikachu'),
    ('piranhaPlant', 77, 'Piranha Plant'),
    ('pit', 32, 'Pit'),
    ('ptCharizard', 38, 'Charizard'),
    ('ptIvysaur', 39, 'Ivysaur'),
    ('ptSquirtle', 40, 'Squirtle'),
    ('pyra', 86, 'Pyra'),
    ('richter', 73, 'Richter'),
    ('ridley', 71, 'Ridley'),
    ('rob', 47, 'Rob'),
    ('robin', 61, 'Robin'),
    ('rosalinaAndLuma', 53, 'Rosalina & Luma'),
    ('roy', 28, 'Roy'),
    ('ryu', 65, 'Ryu'),
    ('samus', 4, 'Samus'),
    ('sephiroth', 85, 'Sephiroth'),
    ('sheik', 18, 'Sheik'),
    ('shulk', 62, 'Shulk'),
    ('simon', 72, 'Simon'),
    ('snake', 36, 'Snake'),
    ('sonic', 43, 'Sonic'),
    ('sora', 89, 'Sora'),
    ('steve', 84, 'Steve');
