INSERT INTO public.moves AS "banjo"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (1, 'jab 1', 'single', 'move'),
    (1, 'jab 2', 'single', 'move'),
    (1, 'jab 3', 'single', 'move'),
    (1, 'rapid jab', 'multi', 'move'),
    (1, 'rapid jab finisher', 'single', 'move'),
    (1, 'forward tilt', 'sweet/close', 'move'),
    (1, 'up tilt', 'single', 'move'),
    (1, 'down tilt', 'sweet/close/late', 'move'),
    (1, 'dash attack', 'early/late', 'move'),
    (1, 'forward smash', 'single', 'move'),
    (1, 'up smash', 'first/multi/final', 'move'),
    (1, 'down smash', 'single', 'move'),
    (1, 'neutral air', 'multi/final', 'move'),
    (1, 'forward air', 'early/late', 'move'),
    (1, 'back air', 'multi/final', 'move'),
    (1, 'up air', 'first/second', 'move'),
    (1, 'down air', 'falling/landing', 'move'),
    (1, 'neutral b', 'early/late/latest', 'move'),
    (1, 'side b', 'early/late', 'move'),
    (1, 'up b', '(charged)', 'move'),
    (1, 'down b', 'contact/explosion', 'move');

INSERT INTO public.moves AS "bayonetta"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (2, 'jab 1', 'single', 'move'),
    (2, 'jab 2', 'single', 'move'),
    (2, 'jab 3', 'single', 'move'),
    (2, 'rapid jab', 'single/multi', 'move'),
    (2, 'rapid jab finisher', 'single', 'move'),
    (2, 'forward tilt 1', 'single', 'move'),
    (2, 'forward tilt 2', 'single', 'move'),
    (2, 'forward tilt 3', 'single', 'move'),
    (2, 'up tilt', 'single/single/final', 'move'),
    (2, 'down tilt', 'close/sweet', 'move'),
    (2, 'dash attack', 'early/late', 'move'),
    (2, 'forward smash', 'sweet/close', 'move'),
    (2, 'up smash', 'early/late/latest', 'move'),
    (2, 'down smash', 'stomp/early/late', 'move'),
    (2, 'neutral air', 'early/late/(extended)', 'move'),
    (2, 'forward air 1', 'single', 'move'),
    (2, 'forward air 2', 'single', 'move'),
    (2, 'forward air 3', 'single', 'move'),
    (2, 'back air', 'sweet/close', 'move'),
    (2, 'up air', 'single/(extended)', 'move'),
    (2, 'down air', 'closest/close/sweet/landing', 'move'),
    (2, 'neutral b', 'multi', 'move'),
    (2, 'neutral b (charged)', 'multi', 'move'),
    (2, 'side b, grounded', 'early/late (second)', 'move'),
    (2, 'side b, angled up', 'early/late/latest', 'move'),
    (2, 'side b, angled down', 'normal/landing', 'move'),
    (2, 'up b', 'first/multi/final', 'move'),
    (2, 'down b', 'counter', 'move');

INSERT INTO public.moves AS "bowser"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (3, 'jab 1', 'single', 'move'),
    (3, 'jab 2', 'single', 'move'),
    (3, 'forward tilt', 'first', 'move'),
    (3, 'up tilt', 'single', 'move'),
    (3, 'down tilt', 'first/second', 'move'),
    (3, 'dash attack', 'early/late', 'move'),
    (3, 'forward smash', 'early/late', 'move'),
    (3, 'up smash', 'sweet/sour/landing', 'move'),
    (3, 'down smash', 'front/back', 'move'),
    (3, 'neutral air', 'multis', 'move'),
    (3, 'forward air', 'sweet/close', 'move'),
    (3, 'back air', 'single', 'move'),
    (3, 'up air', 'single', 'move'),
    (3, 'down air', 'normal/landing', 'move'),
    (3, 'neutral b', 'multi', 'move'),
    (3, 'side b', 'command grab', 'move'),
    (3, 'up b, grounded', 'multi/final', 'move'),
    (3, 'up b, air', 'first/multi/final', 'move'),
    (3, 'down b, grounded', 'rising/falling/landing', 'move'),
    (3, 'down b, air', 'falling/landing', 'move');

INSERT INTO public.moves AS "bowserJr"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (4, 'jab 1', 'single', 'move'),
    (4, 'jab 2', 'single', 'move'),
    (4, 'rapid jab', 'multi', 'move'),
    (4, 'rapid jab finisher', 'single', 'move'),
    (4, 'forward tilt', 'close/sweet', 'move'),
    (4, 'up tilt', 'single', 'move'),
    (4, 'down tilt', 'multi/final', 'move'),
    (4, 'dash attack', 'multi/final', 'move'),
    (4, 'forward smash', 'multi/final', 'move'),
    (4, 'up smash', 'first/multi/final', 'move'),
    (4, 'down smash', 'single', 'move'),
    (4, 'neutral air', 'close (early/late/latest/far)(early/late/later)', 'move'),
    (4, 'forward air', 'early far/early close (mid far/mid close)(late fair/late close)/landiing', 'move'),
    (4, 'back air', 'early far/late far/close', 'move'),
    (4, 'up air', 'early/late', 'move'),
    (4, 'down air', 'multi/final/landing', 'move'),
    (4, 'neutral b', 'early/late', 'move'),
    (4, 'side b, dash', 'single', 'move'),
    (4, 'side b, spinout', 'early-latest', 'move'),
    (4, 'up b, recovery', 'contact/explosion', 'move'),
    (4, 'up b, hammer', 'front/back', 'move'),
    (4, 'down b', 'explosion', 'move');

INSERT INTO public.moves AS "byleth"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (5, 'jab 1', 'single', 'move'),
    (5, 'jab 2', 'single', 'move'),
    (5, 'jab 3', 'single', 'move'),
    (5, 'rapid jab', 'multi', 'move'),
    (5, 'rapid jab finisher', 'single', 'move'),
    (5, 'forward tilt', 'single', 'move'),
    (5, 'up tilt', 'single', 'move'),
    (5, 'down tilt', 'single', 'move'),
    (5, 'dash attack', 'close/sweet', 'move'),
    (5, 'forward smash', 'close/sweet (normal)(down)(up)', 'move'),
    (5, 'up smash', 'first/multi/final', 'move'),
    (5, 'down smash', 'front/back', 'move'),
    (5, 'neutral air', 'multi/final/landing', 'move'),
    (5, 'forward air', 'sweet/close', 'move'),
    (5, 'back air', 'early sweet/close (late sweet/close)', 'move'),
    (5, 'up air', 'multi/final', 'move'),
    (5, 'down air', 'single', 'move'),
    (5, 'neutral b', 'normal/charged', 'move'),
    (5, 'side b', 'sweet/close (air)', 'move'),
    (5, 'up b', 'hit/grab/final (air)', 'move'),
    (5, 'down b', 'single/shockwave (air)', 'move');

INSERT INTO public.moves AS "captainFalcon"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (6, 'jab 1', 'single', 'move'),
    (6, 'jab 2', 'single', 'move'),
    (6, 'jab 3', 'single', 'move'),
    (6, 'rapid jab', 'multi', 'move'),
    (6, 'rapid jab finisher', 'single', 'move'),
    (6, 'forward tilt', 'close/sweet', 'move'),
    (6, 'up tilt', 'single', 'move'),
    (6, 'down tilt', 'single', 'move'),
    (6, 'dash attack', 'early/late', 'move'),
    (6, 'forward smash', 'no angle/angled', 'move'),
    (6, 'up smash', 'close/sweet/second', 'move'),
    (6, 'down smash', 'front/back', 'move'),
    (6, 'neutral air', 'first/second', 'move'),
    (6, 'forward air', 'sweet/close (late)', 'move'),
    (6, 'back air', 'early/late', 'move'),
    (6, 'up air', 'close/far/late', 'move'),
    (6, 'down air', 'single', 'move'),
    (6, 'neutral b', 'ground/reverse (air/reverse)', 'move'),
    (6, 'side b, ground', 'point blank/full', 'move'),
    (6, 'side b, air', 'point blank/full', 'move'),
    (6, 'up b', 'grab/launch', 'move'),
    (6, 'down b, ground', 'early/late/latest', 'move'),
    (6, 'down b, air', 'early/late/latest/landing', 'move');

INSERT INTO public.moves AS "chrom"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (7, 'jab', 'single', 'move'),
    (7, 'forward tilt', 'single', 'move'),
    (7, 'up tilt', 'early/normal/late', 'move'),
    (7, 'down tilt', 'single', 'move'),
    (7, 'dash attack', 'single', 'move'),
    (7, 'forward smash', 'single', 'move'),
    (7, 'up smash', 'first/(multi)/final', 'move'),
    (7, 'down smash', 'front/back', 'move'),
    (7, 'neutral air', 'first/second', 'move'),
    (7, 'forward air', 'single', 'move'),
    (7, 'back air', 'single', 'move'),
    (7, 'up air', 'single', 'move'),
    (7, 'down air', 'sweet/sour', 'move'),
    (7, 'neutral b', '(earliest/latest)', 'move'),
    (7, 'side b (hit 1)', 'single', 'move'),
    (7, 'side b (hit 2), neutral', 'single', 'move'),
    (7, 'side b (hit 3), neutral', 'single', 'move'),
    (7, 'side b (hit 4), neutral', 'single', 'move'),
    (7, 'side b (hit 2), up', 'single', 'move'),
    (7, 'side b (hit 3), up', 'single', 'move'),
    (7, 'side b (hit 4), up', 'single', 'move'),
    (7, 'side b (hit 3), down', 'single', 'move'),
    (7, 'side b (hit 4), down', 'single', 'move'),
    (7, 'up b', 'first/multi/falling/landing', 'move'),
    (7, 'down b, counter', 'counter', 'move'),
    (7, 'down b, attack', 'counter attack', 'move');

INSERT INTO public.moves AS "cloud"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (8, 'jab 1', 'single', 'move'),
    (8, 'jab 2', 'single', 'move'),
    (8, 'jab 3', 'single', 'move'),
    (8, 'forward tilt', 'single', 'move'),
    (8, 'up tilt', 'single', 'move'),
    (8, 'down tilt', 'first/second', 'move'),
    (8, 'dash attack', 'early/late', 'move'),
    (8, 'forward smash', 'first/second/(final close/far', 'move'),
    (8, 'up smash', 'early/late', 'move'),
    (8, 'down smash', 'front/back', 'move'),
    (8, 'neutral air', 'single', 'move'),
    (8, 'forward air', 'early/tipper/late', 'move'),
    (8, 'back air', 'single', 'move'),
    (8, 'up air', 'early/late', 'move'),
    (8, 'down air', 'early/late', 'move'),
    (8, 'neutral b', 'early/late (air early/late)', 'move'),
    (8, 'neutral b, limit', 'first/multi/final', 'move'),
    (8, 'side b, (hit 1)', 'single', 'move'),
    (8, 'side b, (hit 2)', 'single', 'move'),
    (8, 'side b, (hit 3)', 'first/second/third', 'move'),
    (8, 'side b, limit', 'hits 1-2/3-4/final', 'move'),
    (8, 'up b, rising', 'first/second', 'move'),
    (8, 'up b, falling', 'first/landing', 'move'),
    (8, 'up b, limit', 'falling/landing', 'move'),
    (8, 'down b, charged', 'ground (air)', 'move');

INSERT INTO public.moves AS "corrin"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (9, 'jab 1', 'close/tipper', 'move'),
    (9, 'jab 2', 'single', 'move'),
    (9, 'jab 3', 'close/tipper', 'move'),
    (9, 'rapid jab', 'multi', 'move'),
    (9, 'rapid jab finisher', 'single', 'move'),
    (9, 'forward tilt', 'single', 'move'),
    (9, 'up tilt', 'single', 'move'),
    (9, 'down tilt', 'single', 'move'),
    (9, 'dash attack', '(multi)/final', 'move'),
    (9, 'forward smash', 'charging/close/far/tipper', 'move'),
    (9, 'up smash', 'close/far/tipper', 'move'),
    (9, 'down smash', 'front/back/tipper', 'move'),
    (9, 'neutral air', 'early/late', 'move'),
    (9, 'forward air', 'single', 'move'),
    (9, 'back air', 'early/late', 'move'),
    (9, 'up air', 'first', 'move'),
    (9, 'down air', 'falling/landing', 'move'),
    (9, 'neutral b, projectile', 'charge/release', 'move'),
    (9, 'neutral b, chomp', 'charge/release', 'move'),
    (9, 'side b, pin', 'single', 'move'),
    (9, 'side b, pin (air)', 'close/tipper', 'move'),
    (9, 'side b, pin cancel', 'ground contact/air contact', 'move'),
    (9, 'side b, pin jump', null, 'move'),
    (9, 'side b, pin kick', 'early/late (over edge)', 'move'),
    (9, 'side b, back kick', 'early/late (over edge)', 'move'),
    (9, 'up b', 'first/(multi)/final', 'move'),
    (9, 'down b', 'counter', 'move'),
    (9, 'down b', 'counter attack', 'move');

INSERT INTO public.moves AS "daisy"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (10, 'jab 1', 'single', 'move'),
    (10, 'jab 2', 'single', 'move'),
    (10, 'forward tilt', 'close/mid hit/late', 'move'),
    (10, 'up tilt', 'close/far', 'move'),
    (10, 'down tilt', 'single', 'move'),
    (10, 'dash attack', 'first/second', 'move'),
    (10, 'forward smash', 'golf/tennis/pan', 'move'),
    (10, 'up smash', 'early tip/early hand/early sides/late tip/late hand', 'move'),
    (10, 'down smash', 'multi/final', 'move'),
    (10, 'neutral air', 'early/late hands/late hips', 'move'),
    (10, 'forward air', 'close/far', 'move'),
    (10, 'back air', 'early/late', 'move'),
    (10, 'up air', 'first/second', 'move'),
    (10, 'down air', 'multi far/multi close/final', 'move'),
    (10, 'neutral b', 'counter', 'move'),
    (10, 'neutral b', 'counter attack', 'move'),
    (10, 'side b, ground', '(endlag on hit) normal/over edge', 'move'),
    (10, 'side b, air', '(endlag on hit)', 'move'),
    (10, 'up b', 'first/multi/final', 'move'),
    (10, 'down b', 'slot machine', 'move');

INSERT INTO public.moves AS "darkPit"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (11, 'jab 1', 'single', 'move'),
    (11, 'jab 2', 'single', 'move'),
    (11, 'jab 3', 'single', 'move'),
    (11, 'rapid jab', 'multi', 'move'),
    (11, 'rapid jab finisher', 'single', 'move'),
    (11, 'forward tilt', 'close/tipper', 'move'),
    (11, 'up tilt', 'first/second', 'move'),
    (11, 'down tilt', 'single', 'move'),
    (11, 'dash attack', 'single', 'move'),
    (11, 'forward smash', 'first/second', 'move'),
    (11, 'up smash', 'first/second/third', 'move'),
    (11, 'down smash', 'front/back', 'move'),
    (11, 'neutral air', 'multi/final', 'move'),
    (11, 'forward air', 'multi/final', 'move'),
    (11, 'back air', 'close/tipper', 'move'),
    (11, 'up air', 'multi/final', 'move'),
    (11, 'down air', 'early/late', 'move'),
    (11, 'neutral b', 'ground/ground up/air/air up', 'move'),
    (11, 'side b, ground', 'air/grounded', 'move'),
    (11, 'side b, air', 'air/grounded', 'move'),
    (11, 'up b', 'recovery', 'move'),
    (11, 'down b', 'shield (endlag)', 'move');

INSERT INTO public.moves AS "darkSamus"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (12, 'jab 1', 'single', 'move'),
    (12, 'jab 2', 'single', 'move'),
    (12, 'forward tilt', 'close/middle/far', 'move'),
    (12, 'up tilt', 'late/early', 'move'),
    (12, 'down tilt', 'single', 'move'),
    (12, 'dash attack', 'early/late/latest', 'move'),
    (12, 'forward smash', 'close/far', 'move'),
    (12, 'up smash', 'multi/final', 'move'),
    (12, 'down smash', 'front/back', 'move'),
    (12, 'neutral air', 'hit 1/early hit 2/late', 'move'),
    (12, 'forward air', 'first/multi/final', 'move'),
    (12, 'back air', 'early close/early far/late', 'move'),
    (12, 'up air', 'first/multi/final', 'move'),
    (12, 'down air', 'early/meteor/late', 'move'),
    (12, 'z air', 'first/second', 'move'),
    (12, 'neutral b', '(charge time)', 'move'),
    (12, 'neutral b, full charge', 'single', 'move'),
    (12, 'side b, homing', 'single', 'move'),
    (12, 'side b, super', 'single', 'move'),
    (12, 'up b, ground', 'first/multi/final', 'move'),
    (12, 'up b, air', 'multi', 'move'),
    (12, 'down b', '(total frames: holding down/air)', 'move');

INSERT INTO public.moves AS "diddy"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (13, 'jab 1', 'single', 'move'),
    (13, 'jab 2', 'single', 'move'),
    (13, 'jab 3', 'single', 'move'),
    (13, 'forward tilt', 'early/late', 'move'),
    (13, 'up tilt', 'single', 'move'),
    (13, 'down tilt', 'single', 'move'),
    (13, 'dash attack', 'multi/final', 'move'),
    (13, 'forward smash', 'first/second', 'move'),
    (13, 'up smash', 'first/second/third', 'move'),
    (13, 'down smash', 'front/back', 'move'),
    (13, 'neutral air', 'single', 'move'),
    (13, 'forward air', 'early/late', 'move'),
    (13, 'back air', 'single', 'move'),
    (13, 'up air', 'single', 'move'),
    (13, 'down air', 'early/late', 'move'),
    (13, 'neutral b', 'projectile/melee', 'move'),
    (13, 'neutral b, misfire', 'explosion', 'move'),
    (13, 'side b', 'air/grounded', 'move'),
    (13, 'side b, attack', 'early/late', 'move'),
    (13, 'up b', 'early/late/latest', 'move'),
    (13, 'up b, explosion', 'explosion', 'move'),
    (13, 'down b', 'banana item', 'move');

INSERT INTO public.moves AS "donkey"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (14, 'jab 1', 'single', 'move'),
    (14, 'jab 2', 'single', 'move'),
    (14, 'forward tilt', 'no angle/angled', 'move'),
    (14, 'up tilt', 'single', 'move'),
    (14, 'down tilt', 'single', 'move'),
    (14, 'dash attack', 'early/late', 'move'),
    (14, 'forward smash', 'tipper/close', 'move'),
    (14, 'up smash', 'single', 'move'),
    (14, 'down smash', 'early/late/arms', 'move'),
    (14, 'neutral air', 'early/late', 'move'),
    (14, 'forward air', 'early/late fists/late arms', 'move'),
    (14, 'back air', 'early/late', 'move'),
    (14, 'up air', 'single', 'move'),
    (14, 'down air', 'sweet/close', 'move'),
    (14, 'neutral b', 'charged hit', 'move'),
    (14, 'neutral b', 'full charge hit', 'move'),
    (14, 'side b', 'single', 'move'),
    (14, 'up b, ground', 'first/multi/final', 'move'),
    (14, 'up b, air', 'first/multi/final', 'move'),
    (14, 'down b, ground', 'single [held]', 'move'),
    (14, 'down b, air', 'single [held]', 'move');

INSERT INTO public.moves AS "drMario"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (15, 'jab 1', 'single', 'move'),
    (15, 'jab 2', 'single', 'move'),
    (15, 'jab 3', 'single', 'move'),
    (15, 'forward tilt', 'single', 'move'),
    (15, 'up tilt', 'single', 'move'),
    (15, 'down tilt', 'close/far', 'move'),
    (15, 'dash attack', 'early/late', 'move'),
    (15, 'forward smash', 'close/far', 'move'),
    (15, 'up smash', 'single', 'move'),
    (15, 'down smash', 'front/back', 'move'),
    (15, 'neutral air', 'early/late', 'move'),
    (15, 'forward air', 'early/perfect/late', 'move'),
    (15, 'back air', 'early/late', 'move'),
    (15, 'up air', 'single', 'move'),
    (15, 'down air', 'single', 'move'),
    (15, 'neutral b', 'early/late', 'move'),
    (15, 'side b', 'single (reflector)', 'move'),
    (15, 'up b', 'early/late', 'move'),
    (15, 'down b', 'multi/final', 'move');

INSERT INTO public.moves AS "duckHunt"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (16, 'jab 1', 'single', 'move'),
    (16, 'jab 2', 'single', 'move'),
    (16, 'jab 3', 'single', 'move'),
    (16, 'rapid jab', 'multi', 'move'),
    (16, 'rapid jab finisher', 'single', 'move'),
    (16, 'forward tilt', 'single', 'move'),
    (16, 'up tilt', 'single', 'move'),
    (16, 'down tilt', 'single', 'move'),
    (16, 'dash attack', 'early/late', 'move'),
    (16, 'forward smash', 'multi/final', 'move'),
    (16, 'up smash', 'multi/final', 'move'),
    (16, 'down smash', 'multi/final', 'move'),
    (16, 'neutral air', 'early/late', 'move'),
    (16, 'forward air', 'tipper/close/late', 'move'),
    (16, 'back air', 'tipper/close', 'move'),
    (16, 'up air', 'multi/final', 'move'),
    (16, 'down air', 'first/second', 'move'),
    (16, 'neutral b', 'can/explosion', 'move'),
    (16, 'side b', 'contact', 'move'),
    (16, 'side b, detonation', 'multi/final', 'move'),
    (16, 'up b', 'recovery', 'move'),
    (16, 'down b', 'single', 'move'),
    (16, 'down b', 'single', 'move'),
    (16, 'down b', 'single', 'move'),
    (16, 'down b', 'single', 'move'),
    (16, 'down b', 'single', 'move');

INSERT INTO public.moves AS "falco"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (17, 'jab 1', 'single', 'move'),
    (17, 'jab 2', 'single', 'move'),
    (17, 'rapid jab', 'multi', 'move'),
    (17, 'rapid jab finisher', 'single', 'move'),
    (17, 'forward tilt', 'single', 'move'),
    (17, 'up tilt', 'first/late/second', 'move'),
    (17, 'down tilt', 'close/far/farthest', 'move'),
    (17, 'dash attack', 'early/late', 'move'),
    (17, 'forward smash', 'early/late', 'move'),
    (17, 'up smash', 'first/second', 'move'),
    (17, 'down smash', 'tipper/close', 'move'),
    (17, 'neutral air', 'first/multi/final', 'move'),
    (17, 'forward air', 'multi/final/landing', 'move'),
    (17, 'back air', 'early/late', 'move'),
    (17, 'up air', 'single', 'move'),
    (17, 'down air', 'early/late', 'move'),
    (17, 'neutral b', 'ground/air', 'move'),
    (17, 'side b', 'ground/air', 'move'),
    (17, 'up b', 'multi/dash/multi', 'move'),
    (17, 'down b', 'single/reflector', 'move');

INSERT INTO public.moves AS "fox"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (18, 'jab 1', 'single', 'move'),
    (18, 'jab 2', 'single', 'move'),
    (18, 'rapid jab', 'multi', 'move'),
    (18, 'rapid jab finisher', 'single', 'move'),
    (18, 'forward tilt', 'no angle/angled', 'move'),
    (18, 'up tilt', 'close/far', 'move'),
    (18, 'down tilt', 'close/far', 'move'),
    (18, 'dash attack', 'early/late', 'move'),
    (18, 'forward smash', 'single', 'move'),
    (18, 'up smash', 'early/late', 'move'),
    (18, 'down smash', 'single', 'move'),
    (18, 'neutral air', 'early/late', 'move'),
    (18, 'forward air', 'multi/landing', 'move'),
    (18, 'back air', 'single', 'move'),
    (18, 'up air', 'first/second', 'move'),
    (18, 'down air', 'multi/final/landing', 'move'),
    (18, 'neutral b', 'early/normal/late', 'move'),
    (18, 'neutral b, air', 'early/normal/late', 'move'),
    (18, 'side b', 'ground/air', 'move'),
    (18, 'up b', 'multi/final', 'move'),
    (18, 'down b', 'iframes/reflector', 'move');

INSERT INTO public.moves AS "ganon"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (19, 'jab 1', 'single', 'move'),
    (19, 'forward tilt', 'close/tipper', 'move'),
    (19, 'up tilt', 'early/late explosion (windbox)', 'move'),
    (19, 'down tilt', 'single', 'move'),
    (19, 'dash attack', 'early/late', 'move'),
    (19, 'forward smash', 'single', 'move'),
    (19, 'up smash', 'far/close', 'move'),
    (19, 'down smash', 'front/back', 'move'),
    (19, 'neutral air', '(first early/late)(second early/late)', 'move'),
    (19, 'forward air', 'close/far', 'move'),
    (19, 'back air', 'far/close', 'move'),
    (19, 'up air', '(close)(early)(late)', 'move'),
    (19, 'down air', 'legs/waist', 'move'),
    (19, 'neutral b', 'forward/reversed', 'move'),
    (19, 'neutral b, air', 'forward/reversed', 'move'),
    (19, 'side b', 'grab', 'move'),
    (19, 'side b, on grab', 'single', 'move'),
    (19, 'side b, air', 'grab', 'move'),
    (19, 'side b, air on grab', 'landing', 'move'),
    (19, 'up b', 'grab/attack', 'move'),
    (19, 'up b, grab', 'multi/final', 'move'),
    (19, 'down b', 'close/far', 'move'),
    (19, 'down b, air', 'early/late/landing', 'move');

INSERT INTO public.moves AS "greninja"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (20, 'jab 1', 'single', 'move'),
    (20, 'jab 2', 'single', 'move'),
    (20, 'jab 3', 'single', 'move'),
    (20, 'rapid jab', 'multi', 'move'),
    (20, 'rapid jab finisher', 'single', 'move'),
    (20, 'forward tilt', 'no angle/angled', 'move'),
    (20, 'up tilt', 'single', 'move'),
    (20, 'down tilt', 'single', 'move'),
    (20, 'dash attack', 'single', 'move'),
    (20, 'forward smash', 'single', 'move'),
    (20, 'up smash', 'first/second/late', 'move'),
    (20, 'down smash', 'far/close', 'move'),
    (20, 'down taunt', 'multi', 'move'),
    (20, 'neutral air', 'early/late', 'move'),
    (20, 'forward air', 'single', 'move'),
    (20, 'back air', 'first/second/third', 'move'),
    (20, 'up air', 'multi/final', 'move'),
    (20, 'down air', 'early/late', 'move'),
    (20, 'neutral b', 'partial charge/full charge', 'move'),
    (20, 'side b', 'front/back kick', 'move'),
    (20, 'up b', 'recovery', 'move'),
    (20, 'down b, counter', 'counter', 'move'),
    (20, 'down b, attack', 'horizontal/vertical', 'move');

INSERT INTO public.moves AS "hero"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (21, 'jab 1', 'single', 'move'),
    (21, 'jab 2', 'single', 'move'),
    (21, 'jab 3', 'single', 'move'),
    (21, 'forward tilt 1', 'single', 'move'),
    (21, 'forward tilt 2', 'single', 'move'),
    (21, 'up tilt', 'early/late', 'move'),
    (21, 'down tilt', 'single', 'move'),
    (21, 'dash attack', 'close/far', 'move'),
    (21, 'forward smash', 'normal/crit', 'move'),
    (21, 'up smash', 'normal/crit', 'move'),
    (21, 'down smash', 'normal/crit', 'move'),
    (21, 'neutral air', 'single', 'move'),
    (21, 'forward air', 'early/late', 'move'),
    (21, 'back air', 'early/late', 'move'),
    (21, 'up air', 'single', 'move'),
    (21, 'down air', 'early/late', 'move'),
    (21, 'neutral b, no charge', 'projectile', 'move'),
    (21, 'neutral b, half charge', 'projectile', 'move'),
    (21, 'neutral b, full charge', 'projectile/eruption multi', 'move'),
    (21, 'side b, no charge', 'bolt', 'move'),
    (21, 'side b, half charge', 'bolt', 'move'),
    (21, 'side b, full charge', 'bolt', 'move'),
    (21, 'up b, no charge', 'single', 'move'),
    (21, 'up b, half charge', 'multi/final', 'move'),
    (21, 'up b, full charge', 'multi/final', 'move'),
    (21, 'down b, bang (9MP)', 'projectile/explosion', 'move'),
    (21, 'down b, kaboom(37MP)', 'projectile/windbox/explosion', 'move'),
    (21, 'down b, sizz(8MP)', 'projectile/explosion', 'move'),
    (21, 'down b, sizzle(20MP)', 'projectile/explosion', 'move'),
    (21, 'down b, whack(10MP)', '% based execute chance', 'move'),
    (21, 'down b, twack(30MP)', '% based execute chance', 'move'),
    (21, 'down b, kamikazee(1MP)', 'first/close(far)', 'move'),
    (21, 'down b, magic(allMP) burst', 'multi/final', 'move'),
    (21, 'down b, snooze(16MP)', 'projectile', 'move'),
    (21, 'down b, heal(7MP)', 'buff', 'move'),
    (21, 'down b, oomph(16MP)', 'buff', 'move'),
    (21, 'down b, acceleratle(13MP)', 'buff', 'move'),
    (21, 'down b, bounce(14MP)', 'buff', 'move'),
    (21, 'down b, kaclang(6MP)', 'invulnerability', 'move'),
    (21, 'down b, zoom(8MP)', 'neutral reset', 'move'),
    (21, 'down b, hocus pocus(4MP)', 'rng-ception', 'move'),
    (21, 'down b, flame slash(12MP)', 'single', 'move'),
    (21, 'down b, kacrackle slash(11MP)', 'single', 'move'),
    (21, 'down b, hatchet man(15MP)', 'single', 'move'),
    (21, 'down b, metal slash(6MP)', 'OHKO metal enemies', 'move'),
    (21, 'down b, pysche up(14MP)', 'buff', 'move');

INSERT INTO public.moves AS "iceClimbers"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (22, 'jab 1', 'single', 'move'),
    (22, 'jab 2', 'single', 'move'),
    (22, 'forward tilt', 'single(nana)', 'move'),
    (22, 'up tilt', 'multi/final(nana)', 'move'),
    (22, 'down tilt', 'single(nana)', 'move'),
    (22, 'dash attack', 'single(nana)', 'move'),
    (22, 'forward smash', 'single(nana)', 'move'),
    (22, 'up smash', 'single(nana)', 'move'),
    (22, 'down smash', 'front/(nana: back)', 'move'),
    (22, 'neutral air', 'single(nana)', 'move'),
    (22, 'forward air', 'single(nana)', 'move'),
    (22, 'back air', 'single(nana)', 'move'),
    (22, 'up air', 'single(nana)', 'move'),
    (22, 'down air', 'single(nana)', 'move'),
    (22, 'neutral b', 'projectile(nana)', 'move'),
    (22, 'side b', 'multi/final(nana)', 'move'),
    (22, 'side b, alone', 'multi/final', 'move'),
    (22, 'up b', 'single', 'move'),
    (22, 'down b', 'multi(nana)', 'move');

INSERT INTO public.moves AS "ike"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (23, 'jab 1', 'single', 'move'),
    (23, 'jab 2', 'single', 'move'),
    (23, 'jab 3', 'single', 'move'),
    (23, 'forward tilt', 'single', 'move'),
    (23, 'up tilt', 'early/late', 'move'),
    (23, 'down tilt', 'single', 'move'),
    (23, 'dash attack', 'single', 'move'),
    (23, 'forward smash', 'early/late', 'move'),
    (23, 'up smash', 'early/late', 'move'),
    (23, 'down smash', 'first/second/second late', 'move'),
    (23, 'neutral air', 'early/late', 'move'),
    (23, 'forward air', 'single', 'move'),
    (23, 'back air', 'single', 'move'),
    (23, 'up air', 'single', 'move'),
    (23, 'down air', 'single', 'move'),
    (23, 'neutral b', 'charge', 'move'),
    (23, 'side b', 'charge', 'move'),
    (23, 'up b', 'first/multi/falling/landing', 'move'),
    (23, 'down b', 'counter', 'move');

INSERT INTO public.moves AS "incineroar"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (24, 'jab 1', 'single', 'move'),
    (24, 'jab 2', 'single', 'move'),
    (24, 'jab 3', 'single', 'move'),
    (24, 'forward tilt', 'far/close', 'move'),
    (24, 'up tilt', 'single', 'move'),
    (24, 'down tilt', 'single', 'move'),
    (24, 'dash attack', 'early/late', 'move'),
    (24, 'forward smash', 'close/far', 'move'),
    (24, 'up smash', 'single', 'move'),
    (24, 'down smash', 'single', 'move'),
    (24, 'neutral air', 'early/late', 'move'),
    (24, 'forward air', '(early far/close)/(late far/close)', 'move'),
    (24, 'back air', 'close/far', 'move'),
    (24, 'up air', 'single', 'move'),
    (24, 'down air', '(early far/close)/(late far/close)', 'move'),
    (24, 'neutral b', 'multi/final', 'move'),
    (24, 'side b, grab', 'grab', 'move'),
    (24, 'side b, lariat', 'reactivate', 'move'),
    (24, 'side b, back body drop', 'hold', 'move'),
    (24, 'side b, chest bounce (fail)', 'fail', 'move'),
    (24, 'up b', 'rising/early falling/late falling/landing', 'move'),
    (24, 'down b, counter', 'counter', 'move'),
    (24, 'down b, attack', 'attack', 'move');

INSERT INTO public.moves AS "inkling"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (25, 'jab 1', 'single', 'move'),
    (25, 'jab 2', 'single', 'move'),
    (25, 'jab 3', 'single', 'move'),
    (25, 'rapid jab', 'multi', 'move'),
    (25, 'rapid jab finisher', 'single', 'move'),
    (25, 'forward tilt', 'single', 'move'),
    (25, 'up tilt', 'single', 'move'),
    (25, 'down tilt', 'first/second', 'move'),
    (25, 'dash attack', 'early/late', 'move'),
    (25, 'forward smash', 'close/sweet', 'move'),
    (25, 'up smash', 'first/close/far', 'move'),
    (25, 'down smash', '(front)(back)', 'move'),
    (25, 'neutral air', 'single', 'move'),
    (25, 'forward air', 'tipper/early/late', 'move'),
    (25, 'back air', 'tipper/close', 'move'),
    (25, 'up air', 'first/second', 'move'),
    (25, 'down air', 'sweet/close', 'move'),
    (25, 'neutral b', 'multi', 'move'),
    (25, 'side b', 'air/grounded', 'move'),
    (25, 'up b', 'grounded/air/landing', 'move'),
    (25, 'down b', 'charge', 'move');

INSERT INTO public.moves AS "isabelle"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (26, 'jab', 'single', 'move'),
    (26, 'forward tilt', 'single', 'move'),
    (26, 'up tilt', 'single', 'move'),
    (26, 'down tilt', 'sweet/sour', 'move'),
    (26, 'dash attack', 'early/late', 'move'),
    (26, 'dash attack (off ledge)', 'early/late', 'move'),
    (26, 'forward smash', 'early/late', 'move'),
    (26, 'up smash', 'first/second', 'move'),
    (26, 'down smash', 'front/back', 'move'),
    (26, 'neutral air', 'early/late', 'move'),
    (26, 'forward air', 'early/late/latest', 'move'),
    (26, 'back air', 'early/late/latest', 'move'),
    (26, 'up air', 'early/late', 'move'),
    (26, 'down air', 'early/late', 'move'),
    (26, 'neutral b', 'projectile absorb', 'move'),
    (26, 'neutral b, throw', 'throw', 'move'),
    (26, 'side b, fishing rod', 'ground (air)', 'move'),
    (26, 'side b, reel in', 'grab', 'move'),
    (26, 'side b, forward throw', 'throw', 'move'),
    (26, 'side b, backthrow', 'throw', 'move'),
    (26, 'side b, up throw', 'throw', 'move'),
    (26, 'side b, down throw', 'throw', 'move'),
    (26, 'up b', 'recovery', 'move'),
    (26, 'down b, trap', 'mine', 'move'),
    (26, 'down b, activated', 'multi/final', 'move');

INSERT INTO public.moves AS "jigglypuff"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (27, 'jab 1', 'single', 'move'),
    (27, 'jab 2', 'single', 'move'),
    (27, 'forward tilt', 'single', 'move'),
    (27, 'up tilt', 'early/late', 'move'),
    (27, 'down tilt', 'single', 'move'),
    (27, 'dash attack', 'early/late', 'move'),
    (27, 'forward smash', 'early/late', 'move'),
    (27, 'up smash', 'single', 'move'),
    (27, 'down smash', 'single', 'move'),
    (27, 'neutral air', 'early/late', 'move'),
    (27, 'forward air', 'early/late', 'move'),
    (27, 'back air', 'single', 'move'),
    (27, 'up air', 'single', 'move'),
    (27, 'down air', 'multi/final', 'move'),
    (27, 'neutral b', 'charge', 'move'),
    (27, 'side b', 'single', 'move'),
    (27, 'up b', 'sleep', 'move'),
    (27, 'down b', 'single', 'move');

INSERT INTO public.moves AS "joker"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (28, 'jab 1', 'single (arsene)', 'move'),
    (28, 'jab 2', 'single (arsene)', 'move'),
    (28, 'jab 3', 'single (arsene)', 'move'),
    (28, 'forward tilt', 'first/second (arsene)', 'move'),
    (28, 'up tilt', 'first/multi/final', 'move'),
    (28, 'down tilt', 'late/early', 'move'),
    (28, 'dash attack', 'first/second', 'move'),
    (28, 'forward smash', 'single', 'move'),
    (28, 'up smash', 'single', 'move'),
    (28, 'down smash', 'front/back', 'move'),
    (28, 'neutral air', 'single (front/back)', 'move'),
    (28, 'forward air', 'first/second', 'move'),
    (28, 'back air', 'single', 'move'),
    (28, 'up air', 'multi/final', 'move'),
    (28, 'down air', 'single (Arsene: first/second', 'move'),
    (28, 'neutral b', 'close/med/far', 'move'),
    (28, 'neutral b, arsene', 'close/med/far', 'move'),
    (28, 'side b', 'contact/erupt', 'move'),
    (28, 'side b, arsene', 'contact/erupt', 'move'),
    (28, 'up b (grappling hook)', 'recovery', 'move'),
    (28, 'up b (grappling attack)', 'grounded/air', 'move'),
    (28, 'up b, arsene', 'ground/air', 'move'),
    (28, 'down b, rebel''s guard', 'minimal/additional endlag', 'move'),
    (28, 'down b, counterattack', 'counter', 'move'),
    (28, 'down b, arsene', 'multiplier (minimum/maximum)', 'move');

INSERT INTO public.moves AS "kazuya"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (29, 'jab 1', 'single', 'move'),
    (29, 'jab 2', 'single', 'move'),
    (29, 'jab 3', 'single', 'move'),
    (29, 'jab 4', 'single', 'move'),
    (29, 'jab 5', 'single', 'move'),
    (29, 'jab 6', 'single', 'move'),
    (29, 'jab 7', 'single', 'move'),
    (29, 'jab 8', 'single', 'move'),
    (29, 'jab 9', 'single', 'move'),
    (29, 'jab 10', 'single', 'move'),
    (29, 'a,a,*delay*,a', 'single', 'move'),
    (29, 'forward tilt', 'single', 'move'),
    (29, 'forward-down tilt', 'first/second', 'move'),
    (29, 'down tilt', 'single', 'move'),
    (29, 'down-back tilt', 'single', 'move'),
    (29, 'back tilt', 'single', 'move'),
    (29, 'up-back tilt', 'single', 'move'),
    (29, 'up tilt', 'first/second', 'move'),
    (29, 'up-forward tilt', 'first/second/third/multi', 'move'),
    (29, 'side taunt', 'first/second/third/multi', 'move'),
    (29, '*crouching* down-forward tilt', 'single', 'move'),
    (29, '*crouching* down tilt', 'single', 'move'),
    (29, '*crouching* down-back tilt', 'single', 'move'),
    (29, 'dash attack', 'single', 'move'),
    (29, 'double dash attack', 'single', 'move'),
    (29, 'forward smash', 'close/tipper', 'move'),
    (29, 'up smash', 'early/late', 'move'),
    (29, 'down smash', 'clean hand, late grounded hand/clean arm, late grounded arm/late aerial hand/late aerial arm', 'move'),
    (29, '*uncrouching* attack', 'single', 'move'),
    (29, 'wind god fist', 'single', 'move'),
    (29, 'electric wind god fist', 'single', 'move'),
    (29, 'dragon uppecut', 'early/late/later/latest', 'move'),
    (29, 'spinning dragon to left hook', 'first/second', 'move'),
    (29, 'neutral air', 'tipper/hand/arm/late', 'move'),
    (29, 'forward air', 'early/late', 'move'),
    (29, 'back air', 'sweet/sour/late', 'move'),
    (29, 'up air', 'early/late', 'move'),
    (29, 'down air', 'first/second/landing', 'move'),
    (29, 'neutral b', 'normal/up/down', 'move'),
    (29, 'neutral b, air', 'normal/up/down', 'move'),
    (29, 'side b', 'close/far', 'move'),
    (29, 'up b', 'early-latest', 'move'),
    (29, 'down b', 'command grab', 'move'),
    (29, 'down b, Rage (non-input)', 'command grab', 'move'),
    (29, 'down b, Rage (input)', 'command grab', 'move');

INSERT INTO public.moves AS "ken"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (30, 'jab 1 (light)', 'single', 'move'),
    (30, 'jab 2', 'single', 'move'),
    (30, 'jab 3', 'single', 'move'),
    (30, 'jab (heavy, close)', 'single', 'move'),
    (30, 'jab (heavy, far)', 'single', 'move'),
    (30, 'forward tilt (light, close)', 'single', 'move'),
    (30, 'forward tilt (light, far)', 'single', 'move'),
    (30, 'forward tilt (heavy)', 'close/far', 'move'),
    (30, 'up tilt (light)', 'single', 'move'),
    (30, 'up tilt (heavy)', 'single', 'move'),
    (30, 'down tilt (light)', 'single', 'move'),
    (30, 'down tilt (heavy)', 'sweet/sour', 'move'),
    (30, 'dash attack', 'early/late', 'move'),
    (30, 'forward smash', 'close/far', 'move'),
    (30, 'up smash', 'early/late', 'move'),
    (30, 'down smash', 'sweet/sour', 'move'),
    (30, 'neutral air', 'foot: early/late/knee: early/late', 'move'),
    (30, 'forward air', 'early: foot/knee/late: foot/knee', 'move'),
    (30, 'back air', 'close/far', 'move'),
    (30, 'up air', 'single', 'move'),
    (30, 'down air', 'single', 'move'),
    (30, 'neutral b', 'light/medium/heavy', 'move'),
    (30, 'side b, hit 1', 'single', 'move'),
    (30, 'side b, hit 2-4 (front)', 'multi', 'move'),
    (30, 'side b, hit 2-4 (back)', 'multi', 'move'),
    (30, 'side b, air (front)', 'first/multi', 'move'),
    (30, 'side b, air (back)', 'first/multi', 'move'),
    (30, 'up b', 'early/late', 'move'),
    (30, 'up b, true', 'early/late', 'move'),
    (30, 'up b, flame shoryuken', 'first/second/third', 'move'),
    (30, 'up b, true flame shoryuken', 'first/second/third', 'move'),
    (30, 'down b', 'stage 1/stage 2/stage 3', 'move'),
    (30, 'nata otoshi geri (input)', 'first/second', 'move'),
    (30, 'nata otoshi geri (held input)', 'first/second', 'move'),
    (30, 'oosoto mawashi geri (input)', 'single', 'move'),
    (30, 'oosoto mawashi geri (held input)', 'first/second', 'move');

INSERT INTO public.moves AS "dedede"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (31, 'jab 1', 'single', 'move'),
    (31, 'jab 2', 'single', 'move'),
    (31, 'rapid jab', 'multi', 'move'),
    (31, 'rapid jab finisher', 'single', 'move'),
    (31, 'forward tilt', 'multi/final', 'move'),
    (31, 'up tilt', 'close/far', 'move'),
    (31, 'down tilt', 'early/late', 'move'),
    (31, 'dash attack', 'early/late', 'move'),
    (31, 'forward smash', 'early/close/far/shockwave', 'move'),
    (31, 'up smash', 'single', 'move'),
    (31, 'down smash', 'single', 'move'),
    (31, 'neutral air', 'early/late', 'move'),
    (31, 'forward air', 'single', 'move'),
    (31, 'back air', 'single', 'move'),
    (31, 'up air', 'multi/final', 'move'),
    (31, 'down air', 'meteor/late', 'move'),
    (31, 'neutral b, inhale', 'held', 'move'),
    (31, 'neutral b, spit', 'single', 'move'),
    (31, 'side b', 'hammer/gordo', 'move'),
    (31, 'up b', 'falling/landing/stars', 'move'),
    (31, 'down b, partial charge', 'single', 'move'),
    (31, 'down b, full charge', 'single', 'move');

INSERT INTO public.moves AS "krool"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (32, 'jab 1', 'single', 'move'),
    (32, 'jab 2', 'single', 'move'),
    (32, 'jab 3', 'single', 'move'),
    (32, 'forward tilt', 'close/far', 'move'),
    (32, 'up tilt', 'early/late far/close', 'move'),
    (32, 'down tilt', 'frame 13/close/far', 'move'),
    (32, 'dash attack', 'early/late', 'move'),
    (32, 'forward smash', '(neutral: far/close)/(down: far/close)/(up: far/close)', 'move'),
    (32, 'up smash', 'hit: 1/2/3', 'move'),
    (32, 'down smash', 'body/shockwave', 'move'),
    (32, 'neutral air', 'early/late', 'move'),
    (32, 'forward air', '(early: far/close)/(late: far/close)', 'move'),
    (32, 'back air', 'far/close', 'move'),
    (32, 'up air', 'early/late', 'move'),
    (32, 'down air', 'meteor/late', 'move'),
    (32, 'neutral b', 'projectile', 'move'),
    (32, 'neutral b, second shot', 'projectile', 'move'),
    (32, 'side b', 'throw/return', 'move'),
    (32, 'up b', 'multi', 'move'),
    (32, 'down b, counter', 'counter', 'move'),
    (32, 'down b, counter attack', 'front/reverse', 'move');

INSERT INTO public.moves AS "kirby"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (33, 'jab 1', 'single', 'move'),
    (33, 'jab 2', 'single', 'move'),
    (33, 'rapid jab', 'multi', 'move'),
    (33, 'rapid jab finisher', 'single', 'move'),
    (33, 'forward tilt', 'close/far', 'move'),
    (33, 'up tilt', 'early/late', 'move'),
    (33, 'down tilt', 'single', 'move'),
    (33, 'dash attack', 'early/late/latest', 'move'),
    (33, 'forward smash', 'early/late', 'move'),
    (33, 'up smash', 'close/far/late', 'move'),
    (33, 'down smash', 'early/late', 'move'),
    (33, 'neutral air', 'early/late', 'move'),
    (33, 'forward air', 'first/second/third', 'move'),
    (33, 'back air', 'early/late', 'move'),
    (33, 'up air', 'single', 'move'),
    (33, 'down air', 'multi/final/landing', 'move'),
    (33, 'neutral b, inhale', 'held', 'move'),
    (33, 'neutral b, copy/spit', 'swallow/spit', 'move'),
    (33, 'side b, hammer', 'charge', 'move'),
    (33, 'side b, hammer (full charge)', 'full charge', 'move'),
    (33, 'side b, air', 'first/second', 'move'),
    (33, 'up b', 'rising/falling/landing/projectile', 'move'),
    (33, 'down b', 'single', 'move'),
    (33, 'down b, air', 'single', 'move');

INSERT INTO public.moves AS "link"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (34, 'jab 1', 'single', 'move'),
    (34, 'jab 2', 'single', 'move'),
    (34, 'jab 3', 'single', 'move'),
    (34, 'forward tilt', 'above/front', 'move'),
    (34, 'up tilt', 'single', 'move'),
    (34, 'down tilt', 'single', 'move'),
    (34, 'dash attack', 'single', 'move'),
    (34, 'forward smash, hit 1', 'close/tipper/projectile', 'move'),
    (34, 'forward smash, hit 2', 'single', 'move'),
    (34, 'up smash', 'first/second/third', 'move'),
    (34, 'down smash', 'front/back', 'move'),
    (34, 'neutral air', 'early/late', 'move'),
    (34, 'forward air', 'first/second', 'move'),
    (34, 'back air', 'first/second', 'move'),
    (34, 'up air', 'early/late', 'move'),
    (34, 'down air', 'early/late', 'move'),
    (34, 'neutral b', 'uncharged-full charge', 'move'),
    (34, 'side b', 'clean/late/returning', 'move'),
    (34, 'up b, ground', 'single', 'move'),
    (34, 'up b, air', 'first/multi/final', 'move'),
    (34, 'down b, bomb pull', 'item', 'move'),
    (34, 'down b, bomb detonation', 'explosion', 'move');

INSERT INTO public.moves AS "littleMac"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (35, 'jab 1', 'single', 'move'),
    (35, 'jab 2', 'single', 'move'),
    (35, 'jab 3', 'single', 'move'),
    (35, 'rapid jab', 'multi', 'move'),
    (35, 'rapid jab finisher', 'single', 'move'),
    (35, 'forward tilt', 'first/second', 'move'),
    (35, 'up tilt', 'single', 'move'),
    (35, 'down tilt', 'single', 'move'),
    (35, 'dash attack', 'single', 'move'),
    (35, 'forward smash', 'normal/up/down', 'move'),
    (35, 'up smash', 'early/late', 'move'),
    (35, 'down smash', 'single', 'move'),
    (35, 'neutral air', 'single', 'move'),
    (35, 'forward air', 'single', 'move'),
    (35, 'back air', 'single', 'move'),
    (35, 'up air', 'single', 'move'),
    (35, 'down air', 'meteor/sour', 'move'),
    (35, 'neutral b, partial charge', 'uncharged-charged', 'move'),
    (35, 'neutral b, full charge', 'single', 'move'),
    (35, 'neutral b, K.O. punch', 'ground/air', 'move'),
    (35, 'side b, ground', 'early/late', 'move'),
    (35, 'side b, air', 'early/late', 'move'),
    (35, 'up b', 'first/multi/final', 'move'),
    (35, 'down b, counter', 'counter', 'move'),
    (35, 'down b, counter attack', 'counter attack', 'move');

INSERT INTO public.moves AS "lucario"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (36, 'passive', 'damage when at: 0% | 65% | 190%', 'move'),
    (36, 'jab 1', 'single', 'move'),
    (36, 'jab 2', 'single', 'move'),
    (36, 'jab 3', 'single', 'move'),
    (36, 'forward tilt', 'first/second', 'move'),
    (36, 'up tilt', 'close/far', 'move'),
    (36, 'down tilt', 'single', 'move'),
    (36, 'dash attack', 'early: close/far, late: close/far', 'move'),
    (36, 'forward smash', 'close/far', 'move'),
    (36, 'up smash', 'first/second far/second close', 'move'),
    (36, 'down smash', 'single', 'move'),
    (36, 'neutral air', 'early/late', 'move'),
    (36, 'forward air', 'single', 'move'),
    (36, 'back air', 'early/late', 'move'),
    (36, 'up air', 'far/close', 'move'),
    (36, 'down air', 'first/second', 'move'),
    (36, 'neutral b, partial charge', 'uncharged-charging', 'move'),
    (36, 'neutral b, full charge', 'full charge', 'move'),
    (36, 'side b', 'close/far', 'move'),
    (36, 'side b', 'single', 'move'),
    (36, 'up b', 'on hit', 'move'),
    (36, 'down b, counter', 'counter', 'move'),
    (36, 'down b, counter attack', 'single', 'move');

INSERT INTO public.moves AS "lucas"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (37, 'jab 1', 'single', 'move'),
    (37, 'jab 2', 'single', 'move'),
    (37, 'jab 3', 'single', 'move'),
    (37, 'forward tilt', 'close/far', 'move'),
    (37, 'up tilt', 'first/second/late', 'move'),
    (37, 'down tilt', 'single', 'move'),
    (37, 'dash attack', 'close/far', 'move'),
    (37, 'forward smash', 'close/far', 'move'),
    (37, 'up smash', 'first/main hit/[diminished over time]', 'move'),
    (37, 'down smash', 'first/second/third', 'move'),
    (37, 'neutral air', 'multi/final', 'move'),
    (37, 'forward air', 'close/far', 'move'),
    (37, 'back air', 'close/medium/far', 'move'),
    (37, 'up air', 'single', 'move'),
    (37, 'down air', 'multi/final', 'move'),
    (37, 'z air', 'single', 'move'),
    (37, 'neutral b', 'held', 'move'),
    (37, 'side b', 'spark/burst: close/far', 'move'),
    (37, 'up b', 'head/tail', 'move'),
    (37, 'up b', 'first/multi/final', 'move'),
    (37, 'down b', 'absorb', 'move');

INSERT INTO public.moves AS "lucina"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (38, 'jab 1', 'single', 'move'),
    (38, 'jab 2', 'single', 'move'),
    (38, 'forward tilt', 'single', 'move'),
    (38, 'up tilt', 'early/late', 'move'),
    (38, 'down tilt', 'single', 'move'),
    (38, 'dash attack', 'single', 'move'),
    (38, 'forward smash', 'single', 'move'),
    (38, 'up smash', 'body launcher/sword', 'move'),
    (38, 'down smash', 'front/back', 'move'),
    (38, 'neutral air', 'first/second', 'move'),
    (38, 'forward air', 'single', 'move'),
    (38, 'back air', 'single', 'move'),
    (38, 'up air', 'single', 'move'),
    (38, 'down air', 'sour/meteor', 'move'),
    (38, 'neutral b', 'uncharged-full charge', 'move'),
    (38, 'side b (hit 1)', 'single', 'move'),
    (38, 'side b (hit 2), neutral', 'single', 'move'),
    (38, 'side b (hit 3), neutral', 'single', 'move'),
    (38, 'side b (hit 4), neutral', 'single', 'move'),
    (38, 'side b (hit 2), up', 'single', 'move'),
    (38, 'side b (hit 3), up', 'single', 'move'),
    (38, 'side b (hit 4), up', 'single', 'move'),
    (38, 'side b (hit 3), down', 'single', 'move'),
    (38, 'side b (hit 4), down', 'multi/final', 'move'),
    (38, 'up b', 'early/late', 'move'),
    (38, 'down b, counter', 'counter', 'move'),
    (38, 'down b, counter attack', 'single', 'move');

INSERT INTO public.moves AS "luigi"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (39, 'jab 1', 'single', 'move'),
    (39, 'jab 2', 'single', 'move'),
    (39, 'jab 3', 'single', 'move'),
    (39, 'forward tilt', 'single', 'move'),
    (39, 'up tilt', 'single', 'move'),
    (39, 'down tilt', 'single', 'move'),
    (39, 'dash attack', 'multi/final', 'move'),
    (39, 'forward smash', 'single', 'move'),
    (39, 'up smash', 'far/close', 'move'),
    (39, 'down smash', 'close/far', 'move'),
    (39, 'down taunt', 'meteor', 'move'),
    (39, 'neutral air', 'early/late', 'move'),
    (39, 'forward air', 'single', 'move'),
    (39, 'back air', 'early/late', 'move'),
    (39, 'up air', 'early/late', 'move'),
    (39, 'down air', 'early/late', 'move'),
    (39, 'z air', 'single', 'move'),
    (39, 'neutral b', 'early/late', 'move'),
    (39, 'side b', 'uncharged-charged/misfire', 'move'),
    (39, 'up b, ground', 'sweet/sour', 'move'),
    (39, 'up b, air', 'sweet/sour', 'move'),
    (39, 'down b', 'multi/final', 'move');

INSERT INTO public.moves AS "mario"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (40, 'jab 1', 'single', 'move'),
    (40, 'jab 2', 'single', 'move'),
    (40, 'jab 3', 'single', 'move'),
    (40, 'forward tilt', 'single', 'move'),
    (40, 'up tilt', 'single', 'move'),
    (40, 'down tilt', 'close/far', 'move'),
    (40, 'dash attack', 'early/late', 'move'),
    (40, 'forward smash', 'far/close', 'move'),
    (40, 'up smash', 'single', 'move'),
    (40, 'down smash', 'first/second', 'move'),
    (40, 'neutral air', 'early/late', 'move'),
    (40, 'forward air', 'early/clean/late', 'move'),
    (40, 'back air', 'early/late', 'move'),
    (40, 'up air', 'single', 'move'),
    (40, 'down air', 'multi/final/landing', 'move'),
    (40, 'neutral b', 'early/late', 'move'),
    (40, 'side b', 'single', 'move'),
    (40, 'up b', 'first/multi/final', 'move'),
    (40, 'down b, charging', 'pushback', 'move'),
    (40, 'down b, fully charged', 'pushback', 'move');

INSERT INTO public.moves AS "marth"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (41, 'jab 1', 'close/tipper', 'move'),
    (41, 'jab 2', 'close/tipper', 'move'),
    (41, 'forward tilt', 'close/tipper', 'move'),
    (41, 'up tilt', 'closest/close/tipper', 'move'),
    (41, 'down tilt', 'close/tipper', 'move'),
    (41, 'dash attack', 'closest/close/tipper', 'move'),
    (41, 'forward smash', 'close/tipper', 'move'),
    (41, 'up smash', 'body launcher/close/tipper', 'move'),
    (41, 'down smash', 'front: close/tipper/back: close/tipper', 'move'),
    (41, 'neutral air', 'first: close/tipper/second: close/tipper', 'move'),
    (41, 'forward air', 'close/tipper', 'move'),
    (41, 'back air', 'close/tipper', 'move'),
    (41, 'up air', 'close/tipper', 'move'),
    (41, 'down air', 'close/tipper/meteor', 'move'),
    (41, 'neutral b', 'uncharged-full charge', 'move'),
    (41, 'side b (hit 1)', 'close/tipper', 'move'),
    (41, 'side b (hit 2), neutral', 'close/tipper', 'move'),
    (41, 'side b (hit 3), neutral', 'close/tipper', 'move'),
    (41, 'side b (hit 4), neutral', 'close/tipper', 'move'),
    (41, 'side b (hit 2), up', 'close/tipper', 'move'),
    (41, 'side b (hit 3), up', 'close/tipper', 'move'),
    (41, 'side b (hit 4), up', 'close/tipper', 'move'),
    (41, 'side b (hit 3), down', 'close/tipper', 'move'),
    (41, 'side b (hit 4), down', 'multi/final: close/final: tipper', 'move'),
    (41, 'up b', 'early/late', 'move'),
    (41, 'down b, counter', 'counter', 'move'),
    (41, 'down b, counter attack', 'single', 'move');

INSERT INTO public.moves AS "megaMan"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (42, 'jab, projectile 1', 'canon/projectile early/late', 'move'),
    (42, 'jab, projectile 2', 'canon/projectile early/late', 'move'),
    (42, 'jab, projectile 3', 'canon/projectile early/late', 'move'),
    (42, 'forward tilt, projectile 1', 'canon/projectile early/late', 'move'),
    (42, 'forward tilt, projectile 2', 'canon/projectile early/late', 'move'),
    (42, 'forward tilt, projectile 3', 'canon/projectile early/late', 'move'),
    (42, 'up tilt', 'early/late/later', 'move'),
    (42, 'down tilt', 'early/late', 'move'),
    (42, 'dash attack', 'multi/final', 'move'),
    (42, 'forward smash', 'projectile', 'move'),
    (42, 'up smash', 'firts/multi/final', 'move'),
    (42, 'down smash', 'single', 'move'),
    (42, 'neutral air, projectile 1', 'canon/projectile early/late', 'move'),
    (42, 'neutral air, projectile 2', 'canon/projectile early/late', 'move'),
    (42, 'neutral air, projectile 3', 'canon/projectile early/late', 'move'),
    (42, 'forward air', 'far/close/late', 'move'),
    (42, 'back air', 'first/second/third', 'move'),
    (42, 'up air', 'early/late/final', 'move'),
    (42, 'down air', 'early/meteor', 'move'),
    (42, 'neutral b', 'projectile', 'move'),
    (42, 'side b', 'multi/final', 'move'),
    (42, 'up b', 'recovery', 'move'),
    (42, 'down b, leaf shield', 'multi', 'move'),
    (42, 'down b, throw', 'projectile', 'move');

INSERT INTO public.moves AS "metaKnight"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (43, 'rapid jab', 'multi', 'move'),
    (43, 'rapid jab finisher', 'single', 'move'),
    (43, 'forward tilt 1', 'single', 'move'),
    (43, 'forward tilt 2', 'single', 'move'),
    (43, 'forward tilt 3', 'single', 'move'),
    (43, 'up tilt', 'close/tipper', 'move'),
    (43, 'down tilt', 'single', 'move'),
    (43, 'dash attack', 'early/late', 'move'),
    (43, 'forward smash', 'single', 'move'),
    (43, 'up smash', 'first/second/third', 'move'),
    (43, 'down smash', 'front/back', 'move'),
    (43, 'neutral air', 'early/late', 'move'),
    (43, 'forward air', 'first/second/third', 'move'),
    (43, 'back air', 'first/second/third', 'move'),
    (43, 'up air', 'single', 'move'),
    (43, 'down air', 'single', 'move'),
    (43, 'neutral b', 'early/late', 'move'),
    (43, 'side b', 'multi/final', 'move'),
    (43, 'up b, ground', 'early/late/second', 'move'),
    (43, 'up b, air', 'first/second', 'move'),
    (43, 'down b, dodge', 'i-frames', 'move'),
    (43, 'down b, attack', 'single/i-frames', 'move');

INSERT INTO public.moves AS "mewtwo"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (44, 'jab', 'single', 'move'),
    (44, 'rapid jab', 'multi', 'move'),
    (44, 'rapid jab finisher', 'single', 'move'),
    (44, 'forward tilt', 'close/med/far', 'move'),
    (44, 'up tilt', 'early: close/med/far late: med/far', 'move'),
    (44, 'down tilt', 'close/med/far', 'move'),
    (44, 'dash attack', 'early/late', 'move'),
    (44, 'forward smash', 'close/far', 'move'),
    (44, 'up smash', 'multi/final', 'move'),
    (44, 'down smash', 'single', 'move'),
    (44, 'neutral air', 'multi/final', 'move'),
    (44, 'forward air', 'single', 'move'),
    (44, 'back air', 'close/med/far', 'move'),
    (44, 'up air', 'close/med/far', 'move'),
    (44, 'down air', 'meteor', 'move'),
    (44, 'neutral b, partial charge', 'uncharged-charged', 'move'),
    (44, 'neutral b, full charge', 'fully charged', 'move'),
    (44, 'side b', 'hit/miss', 'move'),
    (44, 'up b', 'recovery', 'move'),
    (44, 'down b', 'stun', 'move');

INSERT INTO public.moves AS "miiBrawler"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (45, 'jab 1', 'single', 'move'),
    (45, 'jab 2', 'single', 'move'),
    (45, 'rapid jab', 'multi', 'move'),
    (45, 'rapid jab finisher', 'single', 'move'),
    (45, 'forward tilt', 'neutral/down/up', 'move'),
    (45, 'up tilt', 'single', 'move'),
    (45, 'down tilt', 'single', 'move'),
    (45, 'dash attack', 'early/late', 'move'),
    (45, 'forward smash', 'single', 'move'),
    (45, 'up smash', 'early/late', 'move'),
    (45, 'down smash', 'single', 'move'),
    (45, 'neutral air', 'single', 'move'),
    (45, 'forward air', 'first/second', 'move'),
    (45, 'back air', 'single', 'move'),
    (45, 'up air', 'single', 'move'),
    (45, 'down air', 'single', 'move'),
    (45, 'shot put', 'falling/after bounce', 'move'),
    (45, 'flashing mach punch', 'multi/final (if hit)', 'move'),
    (45, 'exploding side kick', 'normal/reversed', 'move'),
    (45, 'onslaught, grab (ground)', 'grab', 'move'),
    (45, 'onslaught, success (ground)', 'first/multi/final', 'move'),
    (45, 'onslaught, grab (air)', 'grab', 'move'),
    (45, 'onslaught, success (air)', 'first/multi/final', 'move'),
    (45, 'burning dropkick', 'air/level ground', 'move'),
    (45, 'suplex, grab', 'grab', 'move'),
    (45, 'suplex, success', 'grab/landing', 'move'),
    (45, 'soaring axe kick', 'rising/falling/landing', 'move'),
    (45, 'helicopter kick, ground', 'first/multi/final', 'move'),
    (45, 'helicopter kick, air', 'first/multi/final', 'move'),
    (45, 'thrust uppercut', 'multi/final', 'move'),
    (45, 'head-on assault, ground', 'rising/falling/landing', 'move'),
    (45, 'feint jump', 'flip', 'move'),
    (45, 'feint jump, kick', 'kick/landing', 'move'),
    (45, 'counter throw', 'counter', 'move'),
    (45, 'counter throw, activated', 'throw', 'move');

INSERT INTO public.moves AS "miiGunner"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (46, 'jab 1', 'single', 'move'),
    (46, 'jab 2', 'single', 'move'),
    (46, 'jab 3', 'single', 'move'),
    (46, 'forward tilt', 'early/late/latest', 'move'),
    (46, 'up tilt', 'early: far/close/late: far', 'move'),
    (46, 'down tilt', 'single', 'move'),
    (46, 'dash attack', 'single', 'move'),
    (46, 'forward smash', 'multi/final', 'move'),
    (46, 'up smash', 'first/multi/final', 'move'),
    (46, 'down smash', 'front/back', 'move'),
    (46, 'neutral air', 'single', 'move'),
    (46, 'forward air', 'early/late', 'move'),
    (46, 'back air', 'early/late', 'move'),
    (46, 'up air', 'multi/final', 'move'),
    (46, 'down air', 'early: far/close/late: far/close', 'move'),
    (46, 'charge blast', 'uncharged-charged', 'move'),
    (46, 'laser blaze', 'single', 'move'),
    (46, 'grenade launch', '(grenade) on hit: multi/final', 'move'),
    (46, 'flame pillar', 'multi/final', 'move'),
    (46, 'stealth burst', 'uncharged-charged', 'move'),
    (46, 'gunner missle (homing)', 'projectile', 'move'),
    (46, 'gunner missle (super)', 'projectile', 'move'),
    (46, 'lunar launch', 'single', 'move'),
    (46, 'cannon jump kick', 'first/second/late', 'move'),
    (46, 'echo reflector', 'reflecter', 'move'),
    (46, 'bomb drop', 'contact/explosion', 'move'),
    (46, 'absorbing vortex', 'held', 'move');

INSERT INTO public.moves AS "miiSwordfighter"
  ("fighterId", "name", "moveType", "type")
  VALUES
    (47, 'jab 1', 'single', 'move'),
    (47, 'jab 2', 'single', 'move'),
    (47, 'jab 3', 'single', 'move'),
    (47, 'forward tilt', 'single', 'move'),
    (47, 'up tilt', 'single', 'move'),
    (47, 'down tilt', 'single', 'move'),
    (47, 'dash attack', 'single', 'move'),
    (47, 'forward smash', 'close/far/tipper', 'move'),
    (47, 'up smash', 'first/second/third', 'move'),
    (47, 'down smash', 'front/back', 'move'),
    (47, 'neutral air', 'single', 'move'),
    (47, 'forward air', 'multi/final', 'move'),
    (47, 'back air', 'single', 'move'),
    (47, 'up air', 'early/late', 'move'),
    (47, 'down air', 'multi/landing', 'move'),
    (47, 'gale strike', 'early/late/latest', 'move'),
    (47, 'shuriken of light', 'early/late/later/latest', 'move'),
    (47, 'blurring blade', 'multi/final', 'move'),
    (47, 'airborne assault, ground', 'detection/on hit', 'move'),
    (47, 'airborne assault, air', 'detection/on hit', 'move'),
    (47, 'gale stab', 'uncharged-charged', 'move'),
    (47, 'chakram', 'weak throw/strong throw', 'move'),
    (47, 'stone scabbard', 'rising/falling/landing', 'move'),
    (47, 'skyward slash dash', 'first/multi/final', 'move'),
    (47, 'hero''s spin, ground', 'uncharged-charged | early/late', 'move'),
    (47, 'hero''s spin, air', 'uncharged-charged | first/multi/final', 'move'),
    (47, 'blade counter', 'counter', 'move'),
    (47, 'blade counter, activated', 'counter attack', 'move'),
    (47, 'reversal slash', 'single/reflector', 'move'),
    (47, 'power thrust, ground', 'early/late/latest', 'move'),
    (47, 'power thrust, air', 'falling/landing', 'move');
